Repository AdobeDocs/commerce-pwa-studio, pull requests merged in 2023-05, with the labels that each got.

#183 fix: update PWA's coverage of Adobe Commerce features
  src/pages/integrations/adobe-commerce/features/images/api.svg
  src/pages/integrations/adobe-commerce/features/index.css
  src/pages/integrations/adobe-commerce/features/index.js
Labels: enhancement

#185 Add autodeployment
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: enhancement

#187 Removing note about EPC release timeline.
  src/pages/integrations/adobe-commerce/aep/index.md
Labels: bug

#189 Convert add-to-project-board to reusable workflow
  .github/workflows/add-to-project-board.yml
Labels: enhancement, maintenance
