Repository AdobeDocs/commerce-pwa-studio, pull requests merged in 2023-11, with the labels that each got.

#206 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#207 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#208 Update PWA-AEP integration
  src/pages/integrations/adobe-commerce/aep/index.md
Labels: technical, internal

#211 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies

#210 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  src/pages/guides/general-concepts/routing/index.md
  src/pages/guides/packages/venia/driver-adapter/index.md
  src/pages/guides/project/tools-libraries/index.md
  src/pages/integrations/pagebuilder/custom-components/index.md
  src/pages/integrations/pagebuilder/index.md
  src/pages/troubleshooting/index.md
  src/pages/tutorials/extensions/taglist/index.md
  src/pages/tutorials/index.md
  yarn.lock
Labels: enhancement

#212 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement
