Repository AdobeDocs/commerce-pwa-studio, pull requests merged in 2023-12, with the labels that each got.

#213 GH-156: Fix 404 on next page click
  src/data/navigation/sections/tutorials.js
Labels: maintenance, internal

#214 Recommended steps to install Venia sample data
  src/_includes/images/sample-data-installed.png
  src/_includes/install-venia-sample-data.md
  src/pages/guides/packages/venia/sample-data/images/accessories-sample-data.png
  src/pages/guides/packages/venia/sample-data/images/sample-data-installed.png
  src/pages/guides/packages/venia/sample-data/index.md
  src/pages/metapackages/venia-sample-data/index.md
Labels: major-update, internal

#216 Fix and update workflows with a build step
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .nvmrc
  package.json
Labels: maintenance, internal

#217 Update index.md
  src/pages/metapackages/commerce/index.md
  src/pages/metapackages/open-source/index.md
Labels: technical
