Repository AdobeDocs/commerce-pwa-studio, pull requests merged in 2023-03, with the labels that each got.

#167 Rename magento-devdocs to commerce-docs in links
  src/pages/integrations/adobe-commerce/theme-vs-storefront/index.md
  src/pages/integrations/pagebuilder/custom-components/index.md
  src/pages/tutorials/extensions/taglist/index.md
Labels: maintenance

#168 Prepare for required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  package.json
  yarn.lock
Labels: maintenance

#170 COMDOX-588: Update issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/incorrect_topic.yaml
  .github/ISSUE_TEMPLATE/missing_content.yaml
  .github/ISSUE_TEMPLATE/site_bug.yaml
  .github/ISSUE_TEMPLATE/site_feature.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/index.yml
Labels: maintenance

#172 storefront installation failed with node 18.15.0
  src/pages/tutorials/setup-storefront/index.md
Labels: bug

#174 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: dependencies, maintenance
