Repository AdobeDocs/commerce-pwa-studio, pull requests merged in 2024-01, with the labels that each got.

#221 Revert the PR testing workflow
  .github/workflows/test-pull-request.yml
Labels: maintenance

#220 Update module name
  src/pages/integrations/adobe-commerce/aep/index.md
Labels: editorial

#222 Update index.md
  src/pages/integrations/adobe-commerce/aep/index.md
Labels: editorial

#225 Upgrade theme to v4.11.3
  package.json
  yarn.lock
Labels: dependencies, internal
